In [8]:
# Question 1 : Columns of output matrix are powers of the input vector : Alexandre-Theophile Vandermonde. 

import numpy as np
def vander(m, N=None , increasing=False):
    if N == None:
        N = len(m)
    a=np.zeros((N,N),dtype='int')
    for i in range(N):
        for j in range(0,N):
            if increasing == False:
                a[i][j] = m[i]**(N-j-1)
            else:
                a[i][j] = m[i]**(j)
    return a
inputVector = []
for i in range(int(input('Enter the number of elements in input vector '))):
    inputVector.append(int(input('Enter element {} : '.format(i+1))))

print(vander(inputVector))

Enter the number of elements in input vector 4
Enter element 1 : 2
Enter element 2 : 3
Enter element 3 : 5
Enter element 4 : 1
[[  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [  1   1   1   1]]


In [9]:
# Question 2 : moving average in an array over a window

k = 3
inputValue = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = len(inputValue)
def  movingAverage(n, k, inputValue):
    movingAvgSeqVal = n - k + 1
    y = []
    print('  i  ', end=' ')
    for j in range(1, n+1):
        print(j,end='  ')
    print()
    print('====',' =='*10)
    print('Input',end=' ')
    for j in inputValue:
        print(j,end=' ')
    for i in range(movingAvgSeqVal):
        y.append(int(np.sum(inputValue[i:k+i]) / k))
        print('\ny{}'.format(i+1), ' ', int(np.sum(inputValue[i:k+i]) / k), '= (', inputValue[i], '+', inputValue[i+1], '+',inputValue[k+i-1], ')', '/', k,end='')
movingAverage(n, k, inputValue)

  i   1  2  3  4  5  6  7  8  9  10  11  12  13  
====  == == == == == == == == == ==
Input 3 5 7 2 8 10 11 65 72 81 99 100 150 
y1   5 = ( 3 + 5 + 7 ) / 3
y2   4 = ( 5 + 7 + 2 ) / 3
y3   5 = ( 7 + 2 + 8 ) / 3
y4   6 = ( 2 + 8 + 10 ) / 3
y5   9 = ( 8 + 10 + 11 ) / 3
y6   28 = ( 10 + 11 + 65 ) / 3
y7   49 = ( 11 + 65 + 72 ) / 3
y8   72 = ( 65 + 72 + 81 ) / 3
y9   84 = ( 72 + 81 + 99 ) / 3
y10   93 = ( 81 + 99 + 100 ) / 3
y11   116 = ( 99 + 100 + 150 ) / 3